baseURL = "https://blog.mikail-khan.com/"
languageCode = "en-us"
title = "Mikail Khan"

theme = "hugo-PaperMod"

[Params.homeInfoParams]
Title = "Mikail Khan"
Content = "CS @ Purdue"

[[Params.socialIcons]]
name = "website"
url = "https://mikail-khan.com"

[[Params.socialIcons]]
name = "GitHub"
url = "https://github.com/mkhan45"

[[Params.socialIcons]]
name = "email"
url = "mailto:mikail@mikail-khan.com"

[outputs]
home = ["HTML", "RSS", "JSON"]
